# Buildpack API version
api = "0.10"

# Buildpack ID and metadata
[buildpack]
id = "reenhanced/heroku-buildpack-google-chrome"
version = "0.0.2"
name = "Heroku Buildpack Google Chrome"
description = "Heroku's buildpack for Headless Google Chrome"
homepage = "https://github.com/reenhanced/heroku-buildpack-google-chrome"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"
