# Buildpack API version
api = "0.10"

# Buildpack ID and metadata
[buildpack]
id = "reenhanced/heroku-buildpack-google-chrome"
version = "0.0.2"
name = "Heroku buildpack for Headless Google Chrome. Re-enhanced for external buildpacks"
homepage = "https://github.com/reenhanced/heroku-buildpack-google-chrome"

[[targets]]
arch = "amd64"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"
